### ISSUE TITLE
Julia version under 1s

### ISSUE THREAD

**Issue by oscardssmith** [espadrine/optimal-wordle#3]
Just thought you should know that some tweaks to the algorithm bring the runtime of the Julia version down to about half a second. https://discourse.julialang.org/t/rust-julia-comparison-post/75403/56

**Comment by AbhimanyuAryan** [comment]
@oscardssmith thankyou for sharing this :)

**Comment by espadrine** [comment]
Oh wow, that is amazing! The tricks are fascinating!

I’ll update the code sometime next week.
